#!/bin/sh
# .git/hooks/prepare-commit-msg

# $1 = path to commit message file
# $2 = commit source (e.g., message, template, merge, squash)
# $3 = SHA (for commit --amend)

echo prepare-commit-msg "$@"

# Don't bother if the user supplied a message
if [ "$2" = "message" ]; then
  exit 0
elif [ "$2" = "commit" ] && [ -n "$3" ]; then
  # Get current commit message (the last commit)
  current_msg=$(git log -1 --pretty=%B)

  # Read what's in the commit message file
  file_msg=$(cat "$1")

  if [ "$current_msg" = "$file_msg" ]; then
    # This is the only way to check that --no-edit was used
    exit 0
  fi
fi

# Otherwise, generate a default message
PATH=$(yarn bin):$PATH
tsx index.ts > "$1"
